/* Auto-generated by scripts/gen-resources-all.ts. Do not edit. */
import "./contact/index";
import "./contact/note/index";
import "./course/enrolment/courseEnrol";
import "./course/index";
import "./course/instance/index";
