import { z } from "zod";
import { AxcelerateDate, Id, NonNegInt } from "./types";

export const ContactsSearchQuery = z.object({
	q: z.string().optional(),
	offset: NonNegInt.optional(),
	displayLength: z.number().int().positive().max(100).optional(),
	contactEntryDate: AxcelerateDate.optional(),
	lastUpdated: AxcelerateDate.optional(),
	givenName: z.string().optional(),
	surname: z.string().optional(),
	emailAddress: z.string().optional(),
	contactRoleID: z.number().int().optional(),
	contactIDs: z.array(z.number().int()).optional(),
	contactID: z.number().int().optional(),
	optionalID: z.string().optional(),
	DOB: AxcelerateDate.optional(),
});

export const ContactObject = z.object({
	CONTACTID: Id,
	GIVENNAME: z.string().nullable(),
	SURNAME: z.string().nullable(),
	EMAILADDRESS: z.string().nullable(),
	SEX: z.string().nullable(),
	DOB: z.string().nullable(),
	USI: z.string().nullable(),
	USI_VERIFIED: z.boolean(),
	USI_EXEMPTION: z.boolean(),
	TITLE: z.string().nullable(),
	MIDDLENAME: z.string().nullable(),
	PREFERREDNAME: z.string().nullable(),
	LUI: z.string().nullable(),
	TFN_RECORDED: z.boolean(),
	OPTIONALID: z.string().nullable(),
	POSITION: z.string().nullable(),
	SECTION: z.string().nullable(),
	DIVISION: z.string().nullable(),
	ORGANISATION: z.string().nullable(),
	ADDRESS1: z.string().nullable(),
	ADDRESS2: z.string().nullable(),
	CITY: z.string().nullable(),
	STATE: z.string().nullable(),
	POSTCODE: z.string().nullable(),
	COUNTRY: z.string().nullable(),
	SADDRESS1: z.string().nullable(),
	SADDRESS2: z.string().nullable(),
	SCITY: z.string().nullable(),
	SSTATE: z.string().nullable(),
	SPOSTCODE: z.string().nullable(),
	SCOUNTRY: z.string().nullable(),
	PHONE: z.string().nullable(),
	MOBILEPHONE: z.string().nullable(),
	WORKPHONE: z.string().nullable(),
	FAX: z.string().nullable(),
	COMMENT: z.string().nullable(),
	WEBSITE: z.string().nullable(),
	CITIZENSTATUSID: z.number().int().nullable(),
	CITIZENSTATUSNAME: z.string().nullable(),
	COUNTRYOFBIRTHID: z.number().int().nullable(),
	COUNTRYOFBIRTHNAME: z.string().nullable(),
	CITYOFBIRTH: z.string().nullable(),
	COUNTRYOFCITIZENID: z.number().int().nullable(),
	COUNTRYOFCITIZENNAME: z.string().nullable(),
	INDIGENOUSSTATUSID: z.number().int().nullable(),
	INDIGENOUSSTATUSNAME: z.string().nullable(),
	MAINLANGUAGEID: z.number().int().nullable(),
	MAINLANGUAGENAME: z.string().nullable(),
	ENGLISHPROFICIENCYID: z.number().int().nullable(),
	ENGLISHASSISTANCEFLAG: z.boolean().nullable(),
	HIGHESTSCHOOLLEVELID: z.number().int().nullable(),
	HIGHESTSCHOOLLEVELYEAR: z.number().int().nullable(),
	CURRENTSCHOOLLEVEL: z.string().nullable(),
	ATSCHOOLFLAG: z.boolean().nullable(),
	ATSCHOOLNAME: z.string().nullable(),
	PRIOREDUCATIONIDS: z.array(z.string()),
	PRIOREDUCATIONNAMES: z.array(z.string()),
	DISABILITYFLAG: z.boolean().nullable(),
	DISABILITYTYPEIDS: z.array(z.number().int()),
	DISABILITYTYPENAMES: z.array(z.string()),
	LABOURFORCEID: z.number().int().nullable(),
	LABOURFORCENAME: z.string().nullable(),
	EMERGENCYCONTACT: z.string().nullable(),
	EMERGENCYCONTACTRELATION: z.string().nullable(),
	EMERGENCYCONTACTPHONE: z.string().nullable(),
	ANZSCOCODE: z.string().nullable(),
	ANZSICCODE: z.string().nullable(),
	EMPLOYERCONTACTID: z.number().int().nullable(),
	PAYERCONTACTID: z.number().int().nullable(),
	SUPERVISORCONTACTID: z.number().int().nullable(),
	COACHCONTACTID: z.number().int().nullable(),
	AGENTCONTACTID: z.number().int().nullable(),
	CUSTOMFIELD_MYFIELD: z.string().nullable().optional(),
	CUSTOMFIELD_MYMULTIFIELD: z.array(z.string()).optional(),
	CATEGORYIDS: z.array(z.number().int()),
});

export const ContactList = z.array(ContactObject);
