/* Auto-generated by scripts/gen-endpoints-dts.ts. Do not edit. */
import type { Contact } from "../resources/contact/index";
import type { CourseEnrol } from "../resources/course/enrolment/courseEnrol";
import type { Course } from "../resources/course/index";
import type { CourseInstance } from "../resources/course/instance/index";

declare module "axcelerate-client" {
	interface AxcelerateClient {
		contact: Contact;
		course: Course & { enrolment: CourseEnrol; instance: CourseInstance };
	}
}
export {};
