/* Auto-generated by scripts/gen-endpoints-dts.ts. Do not edit. */
import type { Contact } from "../resources/contact";
import type { Course } from "../resources/course";
import type { CourseDetail } from "../resources/courseDetail";
import type { CourseEnrol } from "../resources/courseEnrol";
import type { CourseInstance } from "../resources/courseInstance";

declare module "axcelerate-client" {
	interface AxcelerateClient {
		contact: Contact;
		course: Course & { detail: CourseDetail; enrolment: CourseEnrol; instance: CourseInstance };
	}
}
export {};
